#name: 'Azure Terraform Pipeline'
#description: 'Azure Terraform generic template '
on:
  workflow_call:
    secrets:
      AZURE_AD_CLIENT_ID: 
        required: true
      AZURE_AD_CLIENT_SECRET: 
        required: true
      AZURE_SUBSCRIPTION_ID: 
        required: true
      AZURE_AD_TENANT_ID: 
        required: true

jobs:
  terraform:
    name: Terraform 
    env:
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - run:  echo  $AZURE_AD_CLIENT_ID 
        shell: bash
      - run:  env 
        shell: bash