#name: 'Azure Terraform Pipeline'
#description: 'Azure Terraform generic template '
on:
  workflow_call

jobs:
  terraform:
    name: Terraform 
    runs-on: ubuntu-latest
    steps:
      - run: echo "This worked" 
        shell: bash