#name: 'Azure Terraform Pipeline'
#description: 'Azure Terraform generic template '
on:
  
  workflow_call:
    inputs:
      TF_VERSION:
        type: string
        required: true
      TF_ACTIONS_WORKING_DIR:  
        required: true
        type: string
    secrets:
      AZURE_AD_CLIENT_ID: 
        required: true
      AZURE_AD_CLIENT_SECRET: 
        required: true
      AZURE_SUBSCRIPTION_ID: 
        required: true
      AZURE_AD_TENANT_ID: 
        required: true

jobs:
  terraform:
    name: Terraform 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.TF_VERSION }} 
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - uses: actions/checkout@v2  
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version:  ${{ inputs.TF_VERSION }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: false 

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: false      

            