#name: 'Azure Terraform Pipeline'
#description: 'Azure Terraform generic template '
on:
  
  workflow_call:
    inputs:
      TF_VERSION:
        type: string
        required: true
      TF_ACTIONS_WORKING_DIR:  
        required: true
        type: string
    secrets:
      AZURE_AD_CLIENT_ID: 
        required: true
      AZURE_AD_CLIENT_SECRET: 
        required: true
      AZURE_SUBSCRIPTION_ID: 
        required: true
      AZURE_AD_TENANT_ID: 
        required: true
      TOKEN:  
        required: true
      GIT_SSH_KEY:
        required: true

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Output github 
        run: echo '${{ toJSON(github) }}'
      - name: Output github.event_name 
        run: echo '${{ github.event_name }}'
      - name: Output  github.event.action 
        run: echo '${{ github.event.action }}'
      - name: Output github.event.pull_request.merged 
        run: echo '${{ github.event.pull_request.merged }}'

  terraform:
    name: Terraform 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.TF_ACTIONS_WORKING_DIR }} 
        shell: bash
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      
    steps:
      - uses: actions/checkout@v2  
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GIT_SSH_KEY }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version:  ${{ inputs.TF_VERSION }}
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
     

      - name: Terraform Init
        id: init
        run: terraform init
      

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
   

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color -out=tfplan && terraform show -no-color tfplan 
      

      - name: Add Plan Comment to PR
        id: plancomment
        uses: actions/github-script@v3
        if: github.event_name == 'pull_request'  && github.event.action != 'closed' && github.event.pull_request.merged != true
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
        
            <details><summary>Show Plan</summary>
            
            \`\`\`${process.env.PLAN}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.TF_ACTIONS_WORKING_DIR }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Apply
        #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        if: github.event_name == 'pull_request'  && github.event.action == 'closed' && github.event.pull_request.merged == true
        id: apply
        run: terraform apply -no-color tfplan 

      - name: Add Apply Comment to PR
        id: applycomment
        uses: actions/github-script@v3
        #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        if: github.event_name == 'pull_request'  && github.event.action == 'closed' && github.event.pull_request.merged == true
        env:
          APPLY: "terraform\n${{ steps.apply.outputs.stdout }}"
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const output = `#### Terraform Apply\`${{ steps.apply.outcome }}\`
        
            <details><summary>Show Apply</summary>
            
            \`\`\`${process.env.APPLY}\`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.TF_ACTIONS_WORKING_DIR }}\`, Workflow: \`${{ github.workflow }}\`*`;
              
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
