#name: 'Azure Terraform Pipeline'
#description: 'Azure Terraform generic template '
on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true 
      ARM_CLIENT_SECRET:
        required: true 
      ARM_SUBSCRIPTION_ID: 
        required: true 
      ARM_TENANT_ID: 
        required: true
jobs:
  terraform:
    name: Terraform 
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    steps:
      - run: echo $ARM_TENANT_ID 
        shell: bash
      - run: echo $ARM_SUBSCRIPTION_ID 
        shell: bash
      - run: echo "Done"
        shell: bash